services:
  app:
    build: ./app
    container_name: semantic_app
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_PORT=${REDIS_PORT}
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:8.2.1
    container_name: semantic_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: 
      - redis_data:/data/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASS} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 3

  elastic: 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: semantic_elastic
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ELASTIC_SECURITY}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - elastic_data:/data/elastic
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:${ELASTIC_PASSWORD}", "-fs", "http://localhost:9200/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: semantic_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOST}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elastic


volumes:
  redis_data:
  elastic_data:
